# ${project.name}
# Version: ${project.version}
# Gitgub: https://github.com/mc-serverworld/worldMISF-libs

configinfo:
  api-version: 1
  debug: false

database:
  set: "autoReconnect=true&characterEncoding=utf-8"
  type: mariadb
  host: "127.0.0.1"
  port: 3306
  database: "database"
  username: "root"
  password: "open"