main: com.serverworld.worldDataBase.paperspigot.PaperSpigotworldDataBase
name: ${project.name}
version: ${project.version}
author: mc-serverworld
website: mc-serverworld.com
softdepend: [PlaceholderAPI]
