# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MISF JAVA CI with Maven
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 8
        format: 'YYYYMMDDHHmmss'
    - name: Display structure of downloaded files
      run: ls -R
    - name: Deploy Github Package
      run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn versions:set -DnewVersion=build-${{ github.run_number }} -DprocessAllModules -DgenerateBackupPoms=false versions:commit
          mvn install
      #$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /home/runner/work/worldMISF/worldMISF
    - run: mkdir staging && cp output/*.jar staging
    #- name: worldMISF jars
      #uses: actions/upload-artifact@v1
      #with:
        #name: worldMISF
        #path: staging
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: build-${{ github.run_number }}
        prerelease: false
        title: build-${{ github.run_number }}
        files: staging/*.jar

