name: worldMISF JAVA CI Main
on:
  push:
    branches: [ main ]
jobs:
  serverworldRunner1_openJDK_15_0_2:
    runs-on: [MISF-SERVER-1-GithubRunner-2]
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Set up openJDK 15.0.2 win64
        uses: actions/setup-java@v1
        with:
          java-version: "15.0.2"
          jdkFile: "G:/BuildUtils/Jdk/openJdk/openjdk-15.0.2_windows-x64_bin.zip"
      - name: Maven Install
        run: |
          mkdir -Force -p ~/.m2 
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn versions:set -DnewVersion=build-${{ github.run_number }} -DprocessAllModules -DgenerateBackupPoms=false versions:commit -T90000
          mvn install -T90000 -DskipTests
      - name: Upload Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: build-${{ github.run_number }}
          prerelease: false
          title: build-${{ github.run_number }}
          files: output/*.jar